/* Build the offline teaching examples from the retained, unmodified ORCA files. */
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),R=require('../visualizador/orca-parser.js');
const specs=[
 ['dimero_b97','Dímero de água · DFT','1-agua-dft'],
 ['dimero_b97_cpcm','Dímero de água · DFT/CPCM','2-solvente-implicito'],
 ['agua_dft','Água · DFT','1-agua-dft'],
 ['agua_cpcm','Água · CPCM','2-solvente-implicito'],
 ['etanol_nve','Etanol · 0,5 fs · NVE','3-xtb2-etanol'],
 ['etanol_dt025','Etanol · 0,25 fs','4-timestep'],
 ['etanol_dt200','Etanol · 2 fs','4-timestep'],
 ['etanol_dt500','Etanol · 5 fs · FALHOU','4-timestep'],
 ['etanol_instavel','Etanol · 2,5 fs · instabilidade gradual','4-timestep'],
 ['etanol_corrigido','Etanol · 0,5 fs · corrigido','4-timestep'],
 ['etanol_csvr','Etanol · CSVR · NVT','5-termostato'],
 ['etanol_etapas','Etanol · aquecer e resfriar · 5 ps','5-termostato'],
 ['zn_parede','Zn–en · com parede','7-dinamica-complexo'],
 ['zn_sem_parede','Zn–en · sem parede','7-dinamica-complexo'],
 ['zn_parede_longo','Zn–en · com parede · 2 ps','7-dinamica-complexo'],
 ['zn_sem_parede_longo','Zn–en · sem parede · 2 ps','7-dinamica-complexo'],
 ['agua_c60','H₂O@C₆₀ · 1 ps','8-agua-no-fulereno'],
 ['zn_solvator','SOLVATOR · 6 águas','6-complexo-solvator'],
 ['preparar_complexo','Complexo · antes do SOLVATOR','6-complexo-solvator']
];
const runs={};
for(const [key,label,lesson] of specs){
 const folder=`exercicios/${lesson}/resultados/${key}`,run={key,label,reference:true,files:[],warnings:[]};
 const files=[`${key}.out`,`${key}-md-ener.csv`,`${key}-traj.xyz`,`${key}-colvars.csv`];
 if(key==='zn_solvator')files.push('zn_solvator.solvator.xyz');
 if(key==='preparar_complexo')files.push('preparar_complexo.xyz');
 for(const file of files){const rel=`${folder}/${file}`,full=path.join(root,rel);if(!fs.existsSync(full))continue;
  const parsed=R.parseFile(fs.readFileSync(full,'utf8'),file),slot=parsed.kind==='energy'?'energy':parsed.kind;
  // Comments remain in the original linked XYZ, not duplicated in every bundled frame.
  if(parsed.frames){
   parsed.frames.forEach(f=>delete f.comment);
   // Keep bundled examples small. Original XYZ downloads retain every frame.
   // Keep the small ethanol molecule complete so geometric extrema and the
   // fast O-H vibration are not aliased by the teaching reference preview.
   const stride=key==='etanol_etapas'?1:Math.ceil(parsed.frames.length/1001);
   if(stride>1){const all=parsed.frames;parsed.previewStride=stride;parsed.originalFrameCount=all.length;parsed.frames=all.filter((f,i)=>i%stride===0||i===all.length-1);parsed.warnings.push(`Prévia da referência: 1 a cada ${stride} quadros, mais o último. Baixe/carregue o XYZ original para examinar todos. Tempos e coordenadas preservados, sem interpolação.`);}
  }
  run[slot]=parsed;run.files.push({name:file,path:rel,kind:parsed.kind});
 }
 const issue=R.validateEnergySources(run.energy,run.out);if(issue)throw new Error(key+': '+issue);
 runs[key]=run;
}
const presets={
 water:{runs:['dimero_b97']},solvent:{runs:['dimero_b97','dimero_b97_cpcm']},ethanol:{runs:['etanol_nve']},
 water_single:{runs:['agua_dft']},solvent_single:{runs:['agua_dft','agua_cpcm']},
 timestep:{runs:['etanol_instavel','etanol_corrigido']},timestep_abrupt:{runs:['etanol_dt500','etanol_corrigido']},timestep_accuracy:{runs:['etanol_dt025','etanol_nve','etanol_dt200']},thermostat:{runs:['etanol_etapas']},thermostat_compare:{runs:['etanol_nve','etanol_csvr']},
 solvator:{runs:['zn_solvator','preparar_complexo'],tab:'trajectory'},complex:{runs:['zn_parede_longo','zn_sem_parede_longo']},
 complex_short:{runs:['zn_parede','zn_sem_parede']},fullerene:{runs:['agua_c60'],tab:'trajectory'}
};
fs.writeFileSync(path.join(root,'visualizador/examples.js'),'/* Real ORCA workshop results; generated by scripts/build_viewer_examples.cjs. */\nwindow.AIMD_EXAMPLES = '+JSON.stringify({presets,runs})+';\n');
console.log(`Offline examples: ${Object.keys(runs).length} calculations, ${fs.statSync(path.join(root,'visualizador/examples.js')).size} bytes.`);
