/* Build the offline teaching examples from the retained, unmodified ORCA files. */
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),R=require('../visualizador/orca-parser.js');
const specs=[
 ['agua_dft','Água · DFT','1-agua-dft'],
 ['agua_cpcm','Água · CPCM','2-solvente-implicito'],
 ['etanol_nve','Etanol · 0,5 fs · NVE','3-xtb2-etanol'],
 ['etanol_dt025','Etanol · 0,25 fs','4-timestep'],
 ['etanol_dt200','Etanol · 2 fs','4-timestep'],
 ['etanol_csvr','Etanol · CSVR · NVT','5-termostato'],
 ['zn_parede','Zn–en · com parede','7-dinamica-complexo'],
 ['zn_sem_parede','Zn–en · sem parede','7-dinamica-complexo'],
 ['zn_solvator','SOLVATOR · 6 águas','6-complexo-solvator'],
 ['preparar_complexo','Complexo · antes do SOLVATOR','6-complexo-solvator']
];
const runs={};
for(const [key,label,lesson] of specs){
 const folder=`exercicios/${lesson}/resultados/${key}`,run={key,label,reference:true,files:[],warnings:[]};
 const files=[`${key}.out`,`${key}-md-ener.csv`,`${key}-traj.xyz`,`${key}-colvars.csv`];
 if(key==='zn_solvator')files.push('zn_solvator.solvator.xyz');
 if(key==='preparar_complexo')files.push('preparar_complexo.xyz');
 for(const file of files){const rel=`${folder}/${file}`,full=path.join(root,rel);if(!fs.existsSync(full))continue;
  const parsed=R.parseFile(fs.readFileSync(full,'utf8'),file),slot=parsed.kind==='energy'?'energy':parsed.kind;
  // Comments remain in the original linked XYZ, not duplicated in every bundled frame.
  if(parsed.frames)parsed.frames.forEach(f=>delete f.comment);
  run[slot]=parsed;run.files.push({name:file,path:rel,kind:parsed.kind});
 }
 const issue=R.validateEnergySources(run.energy,run.out);if(issue)throw new Error(key+': '+issue);
 runs[key]=run;
}
const presets={
 water:{runs:['agua_dft']},solvent:{runs:['agua_dft','agua_cpcm']},ethanol:{runs:['etanol_nve']},
 timestep:{runs:['etanol_dt025','etanol_nve','etanol_dt200']},thermostat:{runs:['etanol_nve','etanol_csvr']},
 solvator:{runs:['zn_solvator','preparar_complexo'],tab:'trajectory'},complex:{runs:['zn_parede','zn_sem_parede']}
};
fs.writeFileSync(path.join(root,'visualizador/examples.js'),'/* Real ORCA workshop results; generated by scripts/build_viewer_examples.cjs. */\nwindow.AIMD_EXAMPLES = '+JSON.stringify({presets,runs})+';\n');
console.log(`Offline examples: ${Object.keys(runs).length} calculations, ${fs.statSync(path.join(root,'visualizador/examples.js')).size} bytes.`);
